# Teleco Market Basket - Association Rules and Lift Analysis

#### A1:Proposal of Question

Can we predict related and future purchases based on the purchase of 1 item? This will give us insights for loss leaders, bundling or product placement.

#### A2:Defined Goal

The goal of this effort will be to find at least 1 sku(item)  that has strong relationships to other items and discovering what are the strongest relationships in order to make recommendations on what are the best items to pair for bundling, loss leaders, or product placement.

## Part II: Market Basket Justification

Market basket analysis answers the question, "What are the chances a customer will be one product based on the the purchases of other products they are making." Example of this in action would be; A customer walks into a store and buys frozen chicken breasts, how likely are they to buy tennis shoes, minced garlic, pot sticker, beer, milk etc. 

By understanding stronger associations buyers for a store can work out coupons, loss leaders, product placement or potentially experiment with gaps in inventory. They can also review selling more by bundling items. For example if butter, sugar, and flour have strong assocative  relations and it is found that a weaker seller and association of condensed milk is made, there could be a bundle deal made for all four to help in selling more condensed milk. 


OUTCOME
The ulitmate outcome is finding the relationship between 1 item and relationships to other items. This will be done with 6 steps. 
- 1) Identify the ANTECEDENT(the initial purchase)
- 2) Obtain the CONSEQUENT(SKU purchased after first purchase)
- 3) Display FREQUENCY (how often two items appear side by side in transaction)
- 4) Present the SUPPORT or PROBABILITY(ratio of transactions)
- 5) Collect CONFIDENCE SCORE (ratio SUPPORT of SKU(s) to SUPPORT of SKU(s)  this can be done by dividing the frequency of ANTECEDENT combinations with the CONSEQUENT observation. 
- 6) Calculate LIFT(probablity increase due to CONSEQUENT purchase or ratio of the transactions containing SKU(s)to SKU(s) if they were random and independent.

Visual example of above reference


| ANTECEDENT      | CONSEQUENT | FREQUENCY | SUPPORT | CONFIDENCE | LIFT |
| ----------- | ----------- |-----------|-----------|-----------|-----------|
| CHICKEN      | GARLIC       | 8      | .42 |.8|1.3|

#### B2:Transaction Example

|ITEM ID     | ITEM DESCRIPTION
| ----------- | ----------- |
|Item01|	Logitech M510 Wireless mouse|
|Item02|	HP 63 Ink|
|Item03|	HP 65 ink|
|Item04|	nonda USB C to USB Adapter|
|Item05|	10ft iPHone Charger Cable|
|Item06|	HP 902XL ink|
|Item07|	Creative Pebble 2.0 Speakers|
|Item08|	Cleaning Gel Universal Dust Cleaner|
|Item09|	Micro Center 32GB Memory card|
|Item10|	YUNSONG 3pack 6ft Nylon Lightning Cable|
|Item11|	TopMate C5 Laptop Cooler pad|
|Item12|	Apple USB-C Charger cable|
|Item13|	HyperX Cloud Stinger Headset|
|Item14|	TONOR USB Gaming Microphone|
|Item15|	Dust-Off Compressed Gas 2 pack|
|Item16|	3A USB Type C Cable 3 pack 6FT|
|Item17|	HOVAMP iPhone charger|
|Item18|	SanDisk Ultra 128GB card|
|Item19|	FEEL2NICE 5 pack 10ft Lighning cable|
|Item20|	FEIYOLD Blue light Blocking Glasses|

#### B3:Market Basket Assumption

subset of a frequent itemset is also frequent so if item a and b are frequently purchased together it is assumed that is item c is used as a subset of a and b that is is a frequently purchased item.

## Part III: Data Preparation and Analysis

#### C1:Transforming the Dataset

Import my common libraries

In [1]:
#### LOAD LIBRARIES
##### system
import sys, os
from time import time

##### Data
import pandas as pd
import numpy as np


###### stats
import scipy.stats as stats
import math
import statsmodels.api as sm

##### Visualization
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams.update({'figure.max_open_warning': 0})

#### PreProcessing Test train split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate, train_test_split, StratifiedShuffleSplit, cross_val_score
from sklearn.feature_selection import SelectKBest, SelectPercentile, f_classif
from sklearn.pipeline import Pipeline, make_pipeline, FeatureUnion

#### Evaluation of Models
from sklearn.metrics import accuracy_score, precision_score, f1_score
from sklearn.metrics import mean_squared_error as MSE

load data

In [2]:
file = pd.read_csv('C://Users//msmorris//Desktop//CHURN_VIZ//task3//teleco_market_basket.csv')
file.head()

,Item01,Item02,Item03,Item04,Item05,Item06,Item07,Item08,Item09,Item10,Item11,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Logitech M510 Wireless mouse,HP 63 Ink,HP 65 ink,nonda USB C to USB Adapter,10ft iPHone Charger Cable,HP 902XL ink,Creative Pebble 2.0 Speakers,Cleaning Gel Universal Dust Cleaner,Micro Center 32GB Memory card,YUNSONG 3pack 6ft Nylon Lightning Cable,TopMate C5 Laptop Cooler pad,Apple USB-C Charger cable,HyperX Cloud Stinger Headset,TONOR USB Gaming Microphone,Dust-Off Compressed Gas 2 pack,3A USB Type C Cable 3 pack 6FT,HOVAMP iPhone charger,SanDisk Ultra 128GB card,FEEL2NICE 5 pack 10ft Lighning cable,FEIYOLD Blue light Blocking Glasses
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Apple Lightning to Digital AV Adapter,TP-Link AC1750 Smart WiFi Router,Apple Pencil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
file.dropna(how='all', inplace=True)
file

,Item01,Item02,Item03,Item04,Item05,Item06,Item07,Item08,Item09,Item10,Item11,Item12,Item13,Item14,Item15,Item16,Item17,Item18,Item19,Item20
1,Logitech M510 Wireless mouse,HP 63 Ink,HP 65 ink,nonda USB C to USB Adapter,10ft iPHone Charger Cable,HP 902XL ink,Creative Pebble 2.0 Speakers,Cleaning Gel Universal Dust Cleaner,Micro Center 32GB Memory card,YUNSONG 3pack 6ft Nylon Lightning Cable,TopMate C5 Laptop Cooler pad,Apple USB-C Charger cable,HyperX Cloud Stinger Headset,TONOR USB Gaming Microphone,Dust-Off Compressed Gas 2 pack,3A USB Type C Cable 3 pack 6FT,HOVAMP iPhone charger,SanDisk Ultra 128GB card,FEEL2NICE 5 pack 10ft Lighning cable,FEIYOLD Blue light Blocking Glasses
3,Apple Lightning to Digital AV Adapter,TP-Link AC1750 Smart WiFi Router,Apple Pencil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,UNEN Mfi Certified 5-pack Lightning Cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Cat8 Ethernet Cable,HP 65 ink,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Dust-Off Compressed Gas 2 pack,Screen Mom Screen Cleaner kit,Moread HDMI to VGA Adapter,HP 62XL Tri-Color ink,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14993,SanDisk 32GB Ultra SDHC card,Vsco 70 pack stickers,SanDisk 128GB microSDXC card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14995,Apple Lightning to Digital AV Adapter,Nylon Braided Lightning to USB cable,Apple Pencil,USB 2.0 Printer cable,ARRIS SURFboard SB8200 Cable Modem,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14997,Falcon Dust Off Compressed Gas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,HP 63XL Ink,Apple USB-C Charger cable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15001,Apple Pencil,SanDisk Ultra 128GB card,RUNMUS Gaming Headset,TopMate C5 Laptop Cooler pad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Remove blanks

In [4]:
file= file.stack().groupby(level=0).apply(list).tolist()

In [5]:
from mlxtend.preprocessing import TransactionEncoder

encoder = TransactionEncoder().fit(file)
mba = encoder.transform(file)
mba = pd.DataFrame(mba, columns = encoder.columns_)
mba_clean = mba
mba_clean

,10ft iPHone Charger Cable,10ft iPHone Charger Cable 2 Pack,3 pack Nylon Braided Lightning Cable,3A USB Type C Cable 3 pack 6FT,5pack Nylon Braided USB C cables,ARRIS SURFboard SB8200 Cable Modem,Anker 2-in-1 USB Card Reader,Anker 4-port USB hub,Anker USB C to HDMI Adapter,Apple Lightning to Digital AV Adapter,...,hP 65 Tri-color ink,iFixit Pro Tech Toolkit,iPhone 11 case,iPhone 12 Charger cable,iPhone 12 Pro case,iPhone 12 case,iPhone Charger Cable Anker 6ft,iPhone SE case,nonda USB C to USB Adapter,seenda Wireless mouse
0,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
mba_clean.to_csv('d212_t3.csv')

#### C2:Code Execution

In [8]:
from mlxtend.frequent_patterns import apriori, association_rules
# from apyori import apriori -- too long of processing time
# setting min to 60% of total transactions
mba_a = apriori(mba, min_support=0.001)
mba_a

       support                   itemsets
0     0.009065                        (0)
1     0.050527                        (1)
2     0.005199                        (2)
3     0.042528                        (3)
4     0.019064                        (4)
...        ...                        ...
6773  0.001067      (96, 67, 102, 90, 28)
6774  0.001067      (102, 76, 89, 91, 28)
6775  0.001067      (98, 102, 90, 91, 28)
6776  0.001600      (67, 36, 102, 89, 90)
6777  0.001067  (67, 36, 102, 89, 90, 28)

[6778 rows x 2 columns]

#### C3:Association Rules Table
    The submission includes accurate values for the support, lift, and confidence of the association rules table.

In [9]:
mba_ar = association_rules(mba_a)
mba_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(104, 1)",(28),0.002000,0.238368,0.001866,0.933333,3.915511,0.001390,11.424477
1,"(4, 111)",(41),0.002666,0.079323,0.002533,0.950000,11.976387,0.002321,18.413545
2,"(6, 22)",(28),0.001733,0.238368,0.001466,0.846154,3.549776,0.001053,4.950607
3,"(94, 6)",(90),0.001600,0.129583,0.001333,0.833333,6.430898,0.001126,5.222504
4,"(20, 31)",(102),0.001466,0.174110,0.001200,0.818182,4.699220,0.000945,4.542394
5,"(82, 22)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
6,"(29, 86)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
7,"(88, 69)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
8,"(89, 82)",(28),0.001866,0.238368,0.001600,0.857143,3.595877,0.001155,5.331422
9,"(90, 111)",(54),0.001866,0.071457,0.001600,0.857143,11.995203,0.001466,6.499800
10,"(86, 71)",(90),0.001466,0.129583,0.001200,0.818182,6.313973,0.001010,4.787295
11,"(91, 77)",(102),0.002133,0.174110,0.001733,0.812500,4.666587,0.001362,4.404746
12,"(8, 1, 30)",(28),0.001600,0.238368,0.001333,0.833333,3.495992,0.000952,4.569791
13,"(1, 36, 22)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
14,"(1, 67, 30)",(28),0.002133,0.238368,0.001733,0.812500,3.408592,0.001225,4.062036
15,"(9, 90, 3)",(102),0.001200,0.174110,0.001067,0.888889,5.105326,0.000858,7.433009
16,"(89, 3, 54)",(102),0.001200,0.174110,0.001067,0.888889,5.105326,0.000858,7.433009
17,"(98, 4, 111)",(41),0.001067,0.079323,0.001067,1.000000,12.606723,0.000982,inf
18,"(92, 6, 30)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
19,"(8, 67, 30)",(102),0.002533,0.174110,0.002133,0.842105,4.836624,0.001692,5.230636
20,"(8, 67, 37)",(102),0.001600,0.174110,0.001333,0.833333,4.786243,0.001055,4.955339
21,"(9, 67, 30)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
22,"(9, 67, 91)",(102),0.001733,0.174110,0.001466,0.846154,4.859877,0.001165,5.368284
23,"(89, 10, 30)",(28),0.001200,0.238368,0.001200,1.000000,4.195190,0.000914,inf
24,"(10, 28, 54)",(102),0.001200,0.174110,0.001067,0.888889,5.105326,0.000858,7.433009
25,"(71, 102, 22)",(12),0.001200,0.179709,0.001067,0.888889,4.946258,0.000851,7.382616
26,"(32, 89, 12)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
27,"(12, 28, 111)",(54),0.001466,0.071457,0.001333,0.909091,12.722185,0.001228,10.213971
28,"(28, 54, 111)",(12),0.001600,0.179709,0.001333,0.833333,4.637117,0.001046,4.921744
29,"(16, 89, 15)",(102),0.001600,0.174110,0.001333,0.833333,4.786243,0.001055,4.955339
30,"(67, 54, 30)",(28),0.002266,0.238368,0.001866,0.823529,3.454862,0.001326,4.315913
31,"(92, 54, 30)",(28),0.001200,0.238368,0.001200,1.000000,4.195190,0.000914,inf
32,"(91, 78, 31)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
33,"(89, 91, 37)",(28),0.001466,0.238368,0.001333,0.909091,3.813809,0.000984,8.377950
34,"(56, 41, 28)",(90),0.001200,0.129583,0.001067,0.888889,6.859625,0.000911,7.833755
35,"(73, 28, 84)",(89),0.001200,0.098254,0.001067,0.888889,9.046887,0.000949,8.115718
36,"(28, 76, 84)",(89),0.001466,0.098254,0.001333,0.909091,9.252498,0.001189,9.919211
37,"(90, 76, 98)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
38,"(90, 92, 94)",(28),0.001200,0.238368,0.001067,0.888889,3.729058,0.000781,6.854686
39,"(28, 94, 92)",(90),0.001067,0.129583,0.001067,1.000000,7.717078,0.000928,inf
40,"(41, 98, 54)",(36),0.001200,0.163845,0.001067,0.888889,5.425188,0.000870,7.525397
41,"(1, 90, 67, 30)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
42,"(8, 89, 67, 28)",(102),0.001466,0.174110,0.001200,0.818182,4.699220,0.000945,4.542394
43,"(36, 12, 102, 30)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
44,"(89, 67, 36, 12)",(28),0.001733,0.238368,0.001466,0.846154,3.549776,0.001053,4.950607
45,"(90, 67, 102, 22)",(28),0.001333,0.238368,0.001200,0.900000,3.775671,0.000882,7.616318
46,"(67, 36, 54, 30)",(28),0.001333,0.238368,0.001200,0.900000,3.775671,0.000882,7.616318
47,"(54, 67, 36, 102)",(28),0.002000,0.238368,0.001733,0.866667,3.635831,0.001256,5.712238
48,"(54, 90, 36, 102)",(28),0.001466,0.238368,0.001200,0.818182,3.432428,0.000850,4.188975
49,"(89, 67, 28, 54)",(102),0.002000,0.174110,0.001733,0.866667,4.977693,0.001385,6.194174
50,"(54, 90, 67, 102)",(28),0.001733,0.238368,0.001466,0.846154,3.549776,0.001053,4.950607
51,"(36, 102, 89, 90, 28)",(67),0.001200,0.095321,0.001067,0.888889,9.325253,0.000952,8.142114

#### C4:Top Three Rules

In [10]:
support = mba_ar.sort_values('support')[:3]
confidence = mba_ar.sort_values('confidence', ascending=False)[:3]
lift = mba_ar.sort_values('lift', ascending=False)[0:3]
leverage = mba_ar.sort_values('leverage', ascending=False)[:3]
conviction = mba_ar.sort_values('conviction', ascending=False)[:3]

In [11]:
print('SUPPORT')
support

SUPPORT

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
25,"(71, 102, 22)",(12),0.001200,0.179709,0.001067,0.888889,4.946258,0.000851,7.382616
40,"(41, 98, 54)",(36),0.001200,0.163845,0.001067,0.888889,5.425188,0.000870,7.525397
39,"(28, 94, 92)",(90),0.001067,0.129583,0.001067,1.000000,7.717078,0.000928,inf

In [12]:
print('CONFIDENCE')
confidence

CONFIDENCE

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
17,"(98, 4, 111)",(41),0.001067,0.079323,0.001067,1.0,12.606723,0.000982,inf
39,"(28, 94, 92)",(90),0.001067,0.129583,0.001067,1.0,7.717078,0.000928,inf
31,"(92, 54, 30)",(28),0.001200,0.238368,0.001200,1.0,4.195190,0.000914,inf

In [13]:
print('LIFT')
lift

LIFT

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
27,"(12, 28, 111)",(54),0.001466,0.071457,0.001333,0.909091,12.722185,0.001228,10.213971
17,"(98, 4, 111)",(41),0.001067,0.079323,0.001067,1.000000,12.606723,0.000982,inf
9,"(90, 111)",(54),0.001866,0.071457,0.001600,0.857143,11.995203,0.001466,6.499800

In [14]:
print('LEVERAGE')
leverage

LEVERAGE

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,"(4, 111)",(41),0.002666,0.079323,0.002533,0.950000,11.976387,0.002321,18.413545
19,"(8, 67, 30)",(102),0.002533,0.174110,0.002133,0.842105,4.836624,0.001692,5.230636
9,"(90, 111)",(54),0.001866,0.071457,0.001600,0.857143,11.995203,0.001466,6.499800

In [15]:
print('CONVICTION')
conviction

CONVICTION

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
17,"(98, 4, 111)",(41),0.001067,0.079323,0.001067,1.0,12.606723,0.000982,inf
39,"(28, 94, 92)",(90),0.001067,0.129583,0.001067,1.0,7.717078,0.000928,inf
31,"(92, 54, 30)",(28),0.001200,0.238368,0.001200,1.0,4.195190,0.000914,inf

## Part IV: Data Summary and Implications

#### D1:Significance of Support, Lift, and Confidence Summary

#### SUPPORT
Support results in how popular an item is or shows up in the data. If any item only shows up 1 time out of 5000 it wont give much weight to our analysis. 
Our top 3 items in this case are
- (SanDisk Ultra 128GB card, FEEL2NICE 5 pack 10.)
- (Brother Genuine High Yield Toner Cartridge, F...)
- (Cat8 Ethernet Cable, SanDisk Extreme 256GB card)

#### LIFT
Lift and confidence are similiar in nature but Lift controls for how popular a purchased item may be. 
Lift gives us insight into how likely an items is purchased when another item is purchase in other words
how likely is it that someone will buy X if they purchased Y, controlling for popularity of both x and y
Our top 3 lift scores are
- (Screen Mom Screen Cleaner kit, iPhone 11 case)
- (iPhone 11 case, 5pack Nylon Braided USB C cab..)
- (Anker 2-in-1 USB Card Reader, TP-Link AC1750 ...)

#### CONFIDENCE
Finally Confidence
This shows how likely it is a person will buy item x if they have purchased item y.
- (iPhone 11 case, 5pack Nylon Braided USB C cab...)
- (iPhone 11 case, 5pack Nylon Braided USB C cab..)
- (SanDisk Ultra 128GB card, FEEL2NICE 5 pack 10...)

#### D2:Practical Significance of Findings

We can see from the above data that there are some relationships that can be made for example in our top 3 for lift 
There is the relationship made for:

- (Screen Mom Screen Cleaner kit, iPhone 11 case)
- (iPhone 11 case, 5pack Nylon Braided USB C cab..)
- (Anker 2-in-1 USB Card Reader, TP-Link AC1750 ...)

This process can be automated and used to review not only top 3 but top 10, percentiles. Hidden relationships within our less popular product and it can all be automated into a dashboard for ease of use and reporting.

#### D3:Course of Action

An obvious recommendation is to create a "customers who bought this also bought this" recommendation engine. I think this an opportunity however for our internal buyers to create bundle packages, loss leaders and review options for product placement overall to intrique shoppers and give them better value while increasing sales. 

This can be done by automating the above process and give recommendation to our internal buyers on products that work well together and recommendations based on subets frequency if the product would be a candiate for a bundle, product placement, or loss leader.